USE TestCE
GO
IF EXISTS (SELECT * FROM sys.tables WHERE name = 'T1')
	DROP TABLE T1
GO
IF EXISTS (SELECT * FROM sys.tables WHERE name = 'T2')
	DROP TABLE T2
GO
CREATE TABLE T1 (
	ID1 INT IDENTITY(1,1) PRIMARY KEY,
	ID2 INT
)
GO
SET NOCOUNT ON
GO
INSERT INTO T1 VALUES(1);
INSERT INTO T1 VALUES(2);
GO
CREATE TABLE T2 (
ID3 INT IDENTITY(1,1) PRIMARY KEY,
ID2 INT
)
GO
DECLARE @id2 int
SET @id2=1
WHILE @Id2<=1000
BEGIN
INSERT INTO T2 VALUES(2)
SET @id2 = @id2 +1
END
GO
CREATE INDEX IX_T2_ID2 ON T2 (ID2)
GO
SELECT * FROM T1
SELECT * FROM T2
GO
SELECT *
FROM T1 INNER JOIN T2 ON T1.ID2 = T2.ID2
WHERE T1.ID1 = 1
